import mongoose, { Document, Schema } from 'mongoose';

export interface IChatMessage extends Document {
  _id: mongoose.Types.ObjectId;
  sessionId: mongoose.Types.ObjectId;
  sender: 'user' | 'support';
  senderId?: mongoose.Types.ObjectId; // User ID for support messages
  text: string;
  messageType: 'text' | 'image' | 'file' | 'system';
  attachments?: Array<{
    type: 'image' | 'file';
    url: string;
    name: string;
    size?: number;
    mimeType?: string;
  }>;
  isRead: boolean;
  readAt?: Date;
  isEdited: boolean;
  editedAt?: Date;
  replyTo?: mongoose.Types.ObjectId; // Reply to another message
  metadata?: {
    userAgent?: string;
    ipAddress?: string;
    deliveryStatus?: 'sent' | 'delivered' | 'failed';
    /** True when message was generated by support AI */
    isAi?: boolean;
    /** Mark onboarding/system welcome message for auto-open UX */
    isOnboardingWelcome?: boolean;
  };
  createdAt: Date;
  updatedAt: Date;
}

const ChatMessageSchema = new Schema<IChatMessage>({
  sessionId: {
    type: Schema.Types.ObjectId,
    ref: 'ChatSession',
    required: true,
    index: true
  },
  sender: {
    type: String,
    enum: ['user', 'support'],
    required: true,
    index: true
  },
  senderId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    index: true
  },
  text: {
    type: String,
    required: true,
    maxlength: 2000
  },
  messageType: {
    type: String,
    enum: ['text', 'image', 'file', 'system'],
    default: 'text',
    index: true
  },
  attachments: [{
    type: {
      type: String,
      enum: ['image', 'file'],
      required: true
    },
    url: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    size: Number,
    mimeType: String
  }],
  isRead: {
    type: Boolean,
    default: false,
    index: true
  },
  readAt: {
    type: Date
  },
  isEdited: {
    type: Boolean,
    default: false
  },
  editedAt: {
    type: Date
  },
  replyTo: {
    type: Schema.Types.ObjectId,
    ref: 'ChatMessage'
  },
  metadata: {
    userAgent: String,
    ipAddress: String,
    deliveryStatus: {
      type: String,
      enum: ['sent', 'delivered', 'failed'],
      default: 'sent'
    },
    isAi: { type: Boolean, default: false },
    isOnboardingWelcome: { type: Boolean, default: false }
  }
}, {
  timestamps: true,
  collection: 'chatmessages'
});

// Indexes for efficient queries
ChatMessageSchema.index({ sessionId: 1, createdAt: 1 });
ChatMessageSchema.index({ sender: 1, isRead: 1 });
ChatMessageSchema.index({ createdAt: -1 });

// Pre-save middleware to update session's lastMessageAt
ChatMessageSchema.pre('save', async function(next) {
  if (this.isNew) {
    try {
      await mongoose.model('ChatSession').findByIdAndUpdate(
        this.sessionId,
        { lastMessageAt: this.createdAt || new Date() }
      );
    } catch (error) {
      console.error('Error updating session lastMessageAt:', error);
    }
  }
  next();
});

// Define statics interface
interface ChatMessageModel extends mongoose.Model<IChatMessage> {
  markAsRead(sessionId: mongoose.Types.ObjectId, userId: mongoose.Types.ObjectId): Promise<any>;
  getUnreadCount(userId: mongoose.Types.ObjectId): Promise<number>;
}

// Add statics to schema
ChatMessageSchema.statics = {
  markAsRead: async function(sessionId: mongoose.Types.ObjectId, userId: mongoose.Types.ObjectId) {
    return this.updateMany(
      { 
        sessionId, 
        sender: 'support',
        isRead: false 
      },
      { 
        isRead: true, 
        readAt: new Date() 
      }
    );
  },
  
  getUnreadCount: async function(userId: mongoose.Types.ObjectId) {
    const sessions = await mongoose.model('ChatSession').find({ userId });
    const sessionIds = sessions.map(session => session._id);
    
    return this.countDocuments({
      sessionId: { $in: sessionIds },
      sender: 'support',
      isRead: false
    });
  }
};

export default mongoose.model<IChatMessage, ChatMessageModel>('ChatMessage', ChatMessageSchema);
